spring:
  profiles:
    active: local
  jwt:
    secret: 322b5d9bf25abd93fb6d6f70843f2304ef723d6c3e5fbeb4686905193c1ed6001b98ffc68c6fa721df2a3a6adc5dca4faacaef39781b4dc647e3b5101b2dc244
---
#springdoc:
#  swagger-ui:
#    groups-order: DESC
#    tags-sorter: alpha
#    operations-sorter: method
#    disable-swagger-default-url: true
#    display-request-duration: true
#    defaultModelsExpandDepth: 2
#    defaultModelExpandDepth: 2
#  api-docs:
#    path: /api-docs
#  show-actuator: true
#  default-consumes-media-type: application/json
#  default-produces-media-type: application/json
#  writer-with-default-pretty-printer: true
#  model-and-view-allowed: true
#  paths-to-match:
#    - /api/v1/**
